### PR TITLE
Support CommonJS (Node) and AMD environments

### PR DESCRIPTION
**Pull request by bates64**
```js
const Syn = require('./syn')
// ...
```

### CODE REVIEW

**Comment by towerofnix** [comment]
What is AMD

**Comment by bates64** [comment]
> What is AMD

Basically asynchronous `require`. [RequireJS](http://requirejs.org/docs/whyamd.html) uses it. It's old, but support can't hurt.

**Comment by bates64** [comment]
^ that wasn't broken in Node, but it could well have been in browser CommonJS environments

**Comment by towerofnix** [comment]
Thank you for using my code style :P

**Comment by towerofnix** [comment]
RIP, Support CommonJS (Node) and AMD environments, 2016 to 2022. You lived a long and joyful and syntactically accurate life. :headstone: :sparkles: :shipit:

**Pull request closed without merging**
